#!/usr/bin/env bash
#your domain zone so that the subdomain www points to your load-balancer IP

#variables
domain=$1

if [ "$#" -eq 2 ]
then
    subDomain="$2"
else
    subDomain=("www" "lb-01" "web-01" "web-02")
fi

for i in "${subDomain[@]}"
do
    echo -n "The subdomain $i"
    dig "$i.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{print " is a " $4 " record and points to " $5 }' 
done
