#!/usr/bin/env bash
# Install nginx web server
sudo service nginx stop
sudo apt -y update && sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
