#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
apt-get update
apt-get -y install nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i '45 i \\terror_page 404 /404.html;' /etc/nginx/sites-available/default
service nginx restart
