#!/usr/bin/env bash
# This script says which server is working
apt-get -y update
apt-get -y install nginx
sed -ie "s/^server {$/server {\n\tadd_header X-Served-By \$hostname;/g" /etc/nginx/sites-available/default
service nginx restart