#!/usr/bin/env bash
# This script says which server is working
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -ie "s/^server {$/server {\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=wupToqz1e2g permanent;/g" /etc/nginx/sites-available$
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -ie "s/^server {$/server {\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}/g" /etc/$
sudo sed -ie "s/^server {$/server {\n\tadd_header X-Served-By \$hostname;/g" /etc/nginx/sites-available/default
sudo service nginx restart
