#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get -y update && sudo apt-get -y install haproxy=1.8.\*
sudo bash -c 'echo "backend web-backend
                        balance roundrobin
                        server 906-web-01 104.196.104.147:80 check
                        server 906-web-02 34.73.38.83:80 check" > /etc/haproxy/haproxy.cfg'
sudo bash -c 'echo "frontend http
                        bind *:80
                        mode http
                        default_backend web-backend" > /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
