#!/usr/bin/env bash
# Script that generates a MySQL dump and creates a compressed archive out of it.
if [ $# -ne 0 ]
then
mysqldump -u root -p --all-databases > backup.sql
tar czvf $(date +%d-%m-%Y).tar.gz backup.sql
else
echo "Usage: 5-mysql_backup mydummypassword"
fi
