#!/usr/bin/env bash
# Find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
sudo service nginx stop
tar cf - /etc/nginx/sites-available/default | (cd /etc/nginx/sites-enebled/default;tar xf -)
sudo service nginx start
