#!/usr/bin/env bash
# Find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
sudo service nginx stop
sudo rsync /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx start
