#!/usr/bin/env bash
# Find out what’s keeping your Ubuntu container’s Nginx installation from listening on port 80
sudo service nginx stop
tar cf - /etc/nginx/sites-available/ | (cd /etc/nginx/sites-enebled/;tar xf -)
sudo service nginx start
