#!/usr/bin/env bash
# Info about a holbertonschool file.
if [ -e fn ]
then
    echo "holbertonschool file exists"
    if [ -s fn ]
    then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [ -f fn ]
    then
	echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
