#!/usr/bin/env bash
#Script that configures an Ubuntu server with new requirements.
cp /etc/hosts ~/recon_hosts
sed -i 's/127.0.0.1/127.0.0.2/g' ~/recon_hosts
tee -a ~/recon_hosts <<< "8.8.8.8 facebook.com" > /dev/null
cp -f ~/recon_hosts /etc/hosts
